"""fix capturedAt default v1

Revision ID: 02d17a57ea08
Revises: 22b7dc6d6095
Create Date: 2026-05-18 19:38:29.612267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02d17a57ea08'
down_revision = '22b7dc6d6095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_snapshot', schema=None) as batch_op:
        batch_op.drop_column('capturedAt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_snapshot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capturedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
