"""fix capturedAt default v2

Revision ID: 14bd2042b580
Revises: 02d17a57ea08
Create Date: 2026-05-18 19:38:51.656374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14bd2042b580'
down_revision = '02d17a57ea08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_snapshot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capturedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_snapshot', schema=None) as batch_op:
        batch_op.drop_column('capturedAt')

    # ### end Alembic commands ###
