"""add externalIdSipc source externalName255

Revision ID: 2ebe142e83fa
Revises: 7c1238f183c9
Create Date: 2026-05-10 01:23:40.770011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebe142e83fa'
down_revision = '7c1238f183c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_snapshot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=10), nullable=False))

    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('externalIdSipc', sa.Integer(), nullable=True))

    with op.batch_alter_table('store_product', schema=None) as batch_op:
        batch_op.alter_column('externalName',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_product', schema=None) as batch_op:
        batch_op.alter_column('externalName',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_column('externalIdSipc')

    with op.batch_alter_table('price_snapshot', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
