"""initial migration

Revision ID: 4789f6224365
Revises: 
Create Date: 2026-05-12 20:02:03.061063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4789f6224365'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('brandId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('brandId')
    )
    op.create_table('category',
    sa.Column('categoryId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('categoryId')
    )
    op.create_table('store_chain',
    sa.Column('storeChainId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('storeChainId')
    )
    op.create_table('users',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('passwordHash', sa.String(length=255), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('lastLoginAt', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('email')
    )
    op.create_table('product',
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('brandId', sa.Integer(), nullable=False),
    sa.Column('externalIdCkan', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('normalizedName', sa.String(length=50), nullable=False),
    sa.Column('ean', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('weightValue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=5), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('imageURL', sa.String(length=255), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brandId'], ['brand.brandId'], ),
    sa.PrimaryKeyConstraint('productId')
    )
    op.create_table('shopping_list',
    sa.Column('shoppingListId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('subTotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('shoppingListId')
    )
    op.create_table('store',
    sa.Column('storeId', sa.Integer(), nullable=False),
    sa.Column('storeChainId', sa.Integer(), nullable=False),
    sa.Column('externalIdSipc', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['storeChainId'], ['store_chain.storeChainId'], ),
    sa.PrimaryKeyConstraint('storeId')
    )
    op.create_table('favorite',
    sa.Column('favoriteId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['product.productId'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('favoriteId'),
    sa.UniqueConstraint('userId', 'productId', name='uq_user_product_favorite')
    )
    op.create_table('product_category',
    sa.Column('productCategoryId', sa.Integer(), nullable=False),
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('categoryId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['category.categoryId'], ),
    sa.ForeignKeyConstraint(['productId'], ['product.productId'], ),
    sa.PrimaryKeyConstraint('productCategoryId'),
    sa.UniqueConstraint('productId', 'categoryId', name='uq_product_category')
    )
    op.create_table('store_product',
    sa.Column('storeProductId', sa.Integer(), nullable=False),
    sa.Column('storeId', sa.Integer(), nullable=False),
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('externalSku', sa.String(length=50), nullable=True),
    sa.Column('externalName', sa.String(length=255), nullable=True),
    sa.Column('externalBrand', sa.String(length=50), nullable=True),
    sa.Column('isAvailable', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['product.productId'], ),
    sa.ForeignKeyConstraint(['storeId'], ['store.storeId'], ),
    sa.PrimaryKeyConstraint('storeProductId'),
    sa.UniqueConstraint('storeId', 'productId', name='uq_store_product')
    )
    op.create_table('price_snapshot',
    sa.Column('priceSnapshotId', sa.Integer(), nullable=False),
    sa.Column('storeProductId', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=50), nullable=False),
    sa.Column('capturedAt', sa.DateTime(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['storeProductId'], ['store_product.storeProductId'], ),
    sa.PrimaryKeyConstraint('priceSnapshotId')
    )
    op.create_table('shopping_list_item',
    sa.Column('shoppingListItemId', sa.Integer(), nullable=False),
    sa.Column('shoppingListId', sa.Integer(), nullable=False),
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('selectedStoreProductId', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unitPrice', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('totalPrice', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['product.productId'], ),
    sa.ForeignKeyConstraint(['selectedStoreProductId'], ['store_product.storeProductId'], ),
    sa.ForeignKeyConstraint(['shoppingListId'], ['shopping_list.shoppingListId'], ),
    sa.PrimaryKeyConstraint('shoppingListItemId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_list_item')
    op.drop_table('price_snapshot')
    op.drop_table('store_product')
    op.drop_table('product_category')
    op.drop_table('favorite')
    op.drop_table('store')
    op.drop_table('shopping_list')
    op.drop_table('product')
    op.drop_table('users')
    op.drop_table('store_chain')
    op.drop_table('category')
    op.drop_table('brand')
    # ### end Alembic commands ###
