"""update relations

Revision ID: 7c1238f183c9
Revises: 3feb2ff02e23
Create Date: 2026-05-06 22:36:41.746313

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7c1238f183c9"
down_revision = "3feb2ff02e23"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "users",
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("firstName", sa.String(length=50), nullable=False),
        sa.Column("lastName", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("passwordHash", sa.String(length=255), nullable=False),
        sa.Column("isActive", sa.Boolean(), nullable=False),
        sa.Column("lastLoginAt", sa.DateTime(), nullable=True),
        sa.Column(
            "createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("userId"),
        sa.UniqueConstraint("email"),
    )
    with op.batch_alter_table("favorite", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_user_product_favorite", ["userId", "productId"]
        )
        batch_op.drop_constraint(batch_op.f("favorite_userId_fkey"), type_="foreignkey")
        batch_op.create_foreign_key(None, "users", ["userId"], ["userId"])

    with op.batch_alter_table("product_category", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_product_category", ["productId", "categoryId"]
        )

    with op.batch_alter_table("shopping_list", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("shopping_list_userId_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(None, "users", ["userId"], ["userId"])

    with op.batch_alter_table("store_product", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_store_product", ["storeId", "productId"])

    op.drop_table("user")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("store_product", schema=None) as batch_op:
        batch_op.drop_constraint("uq_store_product", type_="unique")

    with op.batch_alter_table("shopping_list", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("shopping_list_userId_fkey"), "user", ["userId"], ["userId"]
        )

    with op.batch_alter_table("product_category", schema=None) as batch_op:
        batch_op.drop_constraint("uq_product_category", type_="unique")

    with op.batch_alter_table("favorite", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("favorite_userId_fkey"), "user", ["userId"], ["userId"]
        )
        batch_op.drop_constraint("uq_user_product_favorite", type_="unique")

    op.create_table(
        "user",
        sa.Column("userId", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "firstName", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "lastName", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("email", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "passwordHash", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("isActive", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "lastLoginAt", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "createdAt",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updatedAt", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("userId", name=op.f("user_pkey")),
        sa.UniqueConstraint(
            "email",
            name=op.f("user_email_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_table("users")
    # ### end Alembic commands ###
