"""add normalizedName to brand

Revision ID: 8a350e8681db
Revises: aae63ff02b9e
Create Date: 2026-05-20 10:46:31.771839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a350e8681db'
down_revision = 'aae63ff02b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('normalizedName', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_brand_normalizedName'), ['normalizedName'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_normalizedName'))
        batch_op.drop_column('normalizedName')

    # ### end Alembic commands ###
