"""empty message

Revision ID: 90ad9474cfda
Revises: 5bf8f4ac1469
Create Date: 2026-05-11 21:30:19.939072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90ad9474cfda'
down_revision = '5bf8f4ac1469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_snapshot', schema=None) as batch_op:
        batch_op.drop_column('source')

    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_column('externalIdSipc')

    with op.batch_alter_table('store_product', schema=None) as batch_op:
        batch_op.alter_column('externalName',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_product', schema=None) as batch_op:
        batch_op.alter_column('externalName',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('externalIdSipc', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('price_snapshot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=10), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
