"""add google oauth fields

Revision ID: 951e1d5c37a5
Revises: 490d09627796
Create Date: 2026-06-01 21:08:25.023232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951e1d5c37a5'
down_revision = '490d09627796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('googleId', sa.String(length=255), nullable=True))
        batch_op.alter_column('passwordHash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_unique_constraint(None, ['googleId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('passwordHash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('googleId')

    # ### end Alembic commands ###
