"""initial migration

Revision ID: d8a5ebf0dac1
Revises: 
Create Date: 2026-05-18 21:52:58.001373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a5ebf0dac1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer',
    sa.Column('offerId', sa.Integer(), nullable=False),
    sa.Column('storeProductId', sa.Integer(), nullable=False),
    sa.Column('offerType', sa.String(length=15), nullable=False),
    sa.Column('offerPrice', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['storeProductId'], ['store_product.storeProductId'], ),
    sa.PrimaryKeyConstraint('offerId')
    )
    op.create_table('offer_schedule',
    sa.Column('offerScheduleId', sa.Integer(), nullable=False),
    sa.Column('offerId', sa.Integer(), nullable=False),
    sa.Column('dayOfWeek', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offerId'], ['offer.offerId'], ),
    sa.PrimaryKeyConstraint('offerScheduleId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer_schedule')
    op.drop_table('offer')
    # ### end Alembic commands ###
