"""add externalIdSipc source externalName255

Revision ID: f1cd54092c87
Revises: 2ebe142e83fa
Create Date: 2026-05-10 01:37:15.523047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1cd54092c87'
down_revision = '2ebe142e83fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('externalIdCkan', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('externalIdCkan')

    # ### end Alembic commands ###
